import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars for Ethereum Lima Academy
 */
const sidebars: SidebarsConfig = {
  // Rutas: enfocado en planes de estudio y formación
  rutasSidebar: [
    {
      type: 'doc',
      id: 'empieza-aqui',
      label: '📍 Empieza Aquí',
    },
    {
      type: 'category',
      label: '🛤️ Rutas de Aprendizaje',
      link: {
        type: 'generated-index',
        title: 'Rutas de Aprendizaje',
        description: 'Explora nuestros planes de estudio estructurados por niveles y temas.',
        slug: '/rutas',
      },
      items: [{ type: 'autogenerated', dirName: 'rutas' }],
    },
  ],

  // Cursos: unidades educativas específicas
  cursosSidebar: [
    {
      type: 'category',
      label: '📚 Catálogo de Cursos',
      link: {
        type: 'generated-index',
        title: 'Nuestros Cursos',
        description: 'Cursos interactivos y prácticos sobre el ecosistema Ethereum.',
        slug: '/cursos',
      },
      items: [{ type: 'autogenerated', dirName: 'cursos' }],
    },
  ],

  // Recursos: guías de contribución, listas de enlaces, etc.
  recursosSidebar: [
    {
      type: 'category',
      label: '🛠️ Recursos para la Comunidad',
      link: {
        type: 'generated-index',
        title: 'Recursos',
        description: 'Herramientas, guías y recursos útiles para el ecosistema.',
        slug: '/recursos',
      },
      items: [{ type: 'autogenerated', dirName: 'recursos' }],
    },
  ],
};

export default sidebars;
